name = "mulligan-golf-booking"
compatibility_date = "2024-11-20"

[build]
command = "pnpm run build && npx @cloudflare/next-on-pages --skip-vercel-specifics"

[assets]
directory = ".vercel/output/static"

[[routes]]
pattern = "/(.*)"
status_code = 200
